// <auto-generated />
namespace ConCon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createdusertableandroles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdusertableandroles));
        
        string IMigrationMetadata.Id
        {
            get { return "201707102149077_created user table and roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
